version: '3.9'

services:
  backend:
    build: ./backend
    container_name: code-forest-backend
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - CLIENT_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: code-forest-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://backend:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
